variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/${CI_COMMIT_TAG:1}"
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: >-
    -Dhttps.proxyHost=iahlproxy.logistics.corp
    -Dhttps.proxyPort=3128
    -Dhttp.proxyHost=iahlproxy.logistics.corp
    -Dhttp.proxyPort=3128
    -Dhttp.nonProxyHosts="localhost|*.logistics.corp|*.kdc.logistics.corp|*.cevalogistics.com"
  ANT_OPTS: >-
    -Dhttps.proxyHost=iahlproxy.logistics.corp
    -Dhttps.proxyPort=3128
    -Dhttp.proxyHost=iahlproxy.logistics.corp
    -Dhttp.proxyPort=3128
    -Dhttp.nonProxyHosts="localhost|*.logistics.corp|*.kdc.logistics.corp|*.cevalogistics.com"
  DOCKER_REGISTRY: docker-dev-snapshot-local.logistics.corp
  CASSANDRA_VERSION: 3.11.12.4
  GRADLE_RELEASE: -Dbuild.snapshot=false
  ANT_RELEASE: -Drelease=true

stages:
  - publish
  - upload
  - release

publish:
  stage: publish
  image: docker-dev-snapshot-local.logistics.corp/strapdata/elassandra_builder:latest
  before_script:
    - keytool -import -noprompt -trustcacerts -alias cevaroot -file /logistics-corp.pem -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit
    - (cd server/cassandra; ant mvn-install $ANT_RELEASE)
    - (cd server/cassandra; ./mvn-install.sh)
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS --version
  script:
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS assemble $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:reindex:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:lang-mustache:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:percolator:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:parent-join:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:rank-eval:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
    - JAVA_HOME=$JAVA9_HOME ./gradlew $GRADLE_OPTS :modules:transport-netty4:publish -PrepoUsername=$MAVEN_USERNAME  -PrepoPassword=$MAVEN_PASSWORD $GRADLE_RELEASE
  artifacts:
    paths:
      - distribution/tar/build/distributions
      - distribution/zip/build/distributions
  tags:
    - k8s-iah-east

# CI_COMMIT_TAG should be v6.2.3.x
# distribution/tar/build/distributions/elassandra-6.2.3.39.tar.gz
upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - ls -lrt distribution/tar/build/distributions
  script:
    - |
      curl -k --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "distribution/tar/build/distributions/elassandra-${CI_COMMIT_TAG:1}.tar.gz" "${PACKAGE_REGISTRY_URL}/elassandra-${CI_COMMIT_TAG:1}.tar.gz"
  tags:
    - k8s-iah-east

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - env
    - |
      release-cli --additional-ca-cert-bundle $CI_PROJECT_DIR/logistics-corp.pem create \
        --name "Release $CI_COMMIT_TAG" \
        --tag-name "$CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"elassandra-${CI_COMMIT_TAG:1}.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/elassandra-${CI_COMMIT_TAG:1}.tar.gz\"}"
  tags:
    - k8s-iah-east


